import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex">
        <div className="w-full flex flex-row grid grid-cols-6">
          <div className="border border-black-400 mt-2 h-screen col-span-2 bg-indigo-100">
            <h1 className="text-4xl text-center py-10 font-semibold">
              Welcome to <a href="#">Maduka</a>
            </h1>
            <p className="text-center font-normal text-lg">
              Get started by creating a store{" "}
            </p>
          </div>

          <div className="border border-red-200 mt-2 ml-2 col-span-4 p-4 bg-yellow-100">
            <h2 className="text-3xl font-medium m-4">Login &rarr;</h2>
            <p>Find out that which this is</p>
            <label for="name">
              {" "}
              Name
              <input
                className="w-full border-radius-50"
                type="text"
                id="name"
              ></input>
            </label>
            <br></br>
            <label for="name">
              {" "}
              Password
              <input className="w-full" type="password" id="name"></input>
            </label>
            <br></br>
            <button
              type="submit"
              className="bg-blue-300 border-2 border-black-300 mt-4 p-2 w-32 text-white rounded-md"
            >
              Log In
            </button>
            <div className="mt-12 flex justify-between">
              <a href="#">
                {" "}
                <button className="bg-blue-300 border-2 border-black-300 h-8 mt-4 px-3 rounded-md">
                  {" "}
                  Forgot Password{" "}
                </button>{" "}
              </a>
              <a href="#">
                <button className="bg-blue-300 border-2 border-black-300  h-8 mt-4 px-3 rounded-md">
                  {" "}
                  Sign Up{" "}
                </button>{" "}
              </a>
            </div>
          </div>
        </div>
      </main>

      <footer className="border-2 border-black-300 h-10 mt-2 text-center">
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by Nairobi Metropolitan
        </a>
      </footer>
    </div>
  );
}
