import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Maduka Kenya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex">
        <div className="w-full flex flex-row grid grid-cols-6">
          <div className="border border-black-400 mt-2 h-screen col-span-2 bg-indigo-50">
            <h1 className="text-4xl text-center py-10 font-semibold">
              Welcome to <a href="#">Maduka</a>
            </h1>
            <p className="text-center font-normal text-lg">
              Get started by creating a store{" "}
            </p>
          </div>

          <div className="border border-red-200 mt-2 ml-2 col-span-4 p-4 bg-yellow-50">
            <h2 className="text-3xl font-semibold m-4">
              Sign in to your account
            </h2>
            <h3 className="text-lg font-normal ml-4 mt-1">Sign In with</h3>
            <div className="border border-black-300 inline block p-2 flex justify-around ml-4">
              <button className="m-2 border-2 border-black-300 w-24 bg-black-200">
                <a href="#">Google</a>
              </button>
              <button className="m-2 border-2 border-black-300 w-24">
                <a href="#">Twitter</a>
              </button>
              <button className="m-2 border-2 border-black-300 w-24">
                <a href="/dashboard">Facebook</a>
              </button>
            </div>
            <br></br>
            <h3 className="text-lg font-normal m-1 ml-4"> Or continue with</h3>
            <hr className="mb-2"></hr>
            <div className="ml-4">
              <label for="name">
                {" "}
                Username
                <input
                  className="w-1/3 border-radius-50 mt-2 mb-4 block rounded-lg border-2"
                  type="text"
                  id="name"
                ></input>
              </label>
              <br></br>
              <label for="name" className="text-normal">
                {" "}
                Password
                <input
                  className="w-1/3 mt-2 mb-4 block rounded-lg border-2"
                  type="password"
                  id="name"
                ></input>
              </label>
              <br></br>
              <button
                type="submit"
                className="bg-blue-300 border-2 border-black-300 mt-4 p-2 w-1/6 text-white rounded-md text-center"
              >
                Log In
              </button>
            </div>
            <div className="mt-12 flex justify-between ml-4">
              <a href="#">
                {" "}
                <button className="border-gray-900 border-b-2 h-8 mt-4 px-1 rounded-none border-opacity-50">
                  {" "}
                  Forgot Password{" "}
                </button>{" "}
              </a>
              <a href="#">
                <button className="border-gray-900 border-b-2 h-8 mt-4 px-1 rounded-none text-black border-opacity-50">
                  {" "}
                  Sign Up{" "}
                </button>{" "}
              </a>
            </div>
          </div>
        </div>
      </main>

      <footer className="border-2 border-black-300 h-10 mt-2 text-center">
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by Nairobi Metropolitan Services
        </a>
      </footer>
    </div>
  );
}
